import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  foundationsSidebar:   [{type: 'autogenerated', dirName: '01-foundations'}],
  evaluationSidebar:    [{type: 'autogenerated', dirName: '02-evaluation'}],
  clinicalSidebar:      [{type: 'autogenerated', dirName: '03-clinical-conditions'}],
  surgicalSidebar:      [{type: 'autogenerated', dirName: '04-surgical-techniques'}],
  populationsSidebar:   [{type: 'autogenerated', dirName: '05-special-populations'}],
  rootsSidebar:         [{type: 'autogenerated', dirName: '07-roots'}],
  // Manual sidebar mirroring the Resources landing page (docs/08-resources/index.mdx)
  // section-stack — same items in the same order. History & Lineage lives in its
  // own section (07-roots) and is linked here; the patient handout gallery is
  // reached from Patient Resources.
  resourcesSidebar: [
    'resources/index',
    'resources/patient-resources',
    'resources/flashcards',
    'resources/journal-club',
    'resources/surgical-video-atlases',
    'resources/podcasts',
    'resources/textbooks',
    'resources/websites-online-tools',
    {
      type: 'category',
      label: 'Hidden Curriculum',
      link: {type: 'doc', id: 'resources/hidden-curriculum/index'},
      items: [{type: 'autogenerated', dirName: '08-resources/hidden-curriculum'}],
    },
    {type: 'link', label: 'History & Lineage', href: '/docs/roots'},
  ],
};

export default sidebars;
