import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  foundationsSidebar:   [{type: 'autogenerated', dirName: '01-foundations'}],
  evaluationSidebar:    [{type: 'autogenerated', dirName: '02-evaluation'}],
  clinicalSidebar:      [{type: 'autogenerated', dirName: '03-clinical-conditions'}],
  surgicalSidebar:      [{type: 'autogenerated', dirName: '04-surgical-techniques'}],
  populationsSidebar:   [{type: 'autogenerated', dirName: '05-special-populations'}],
  journalSidebar:       [{type: 'autogenerated', dirName: '06-journal-club'}],
  rootsSidebar:         [{type: 'autogenerated', dirName: '07-roots'}],
  resourcesSidebar:     [{type: 'autogenerated', dirName: '08-resources'}],
  hiddenCurriculumSidebar: [{type: 'autogenerated', dirName: '09-hidden-curriculum'}],
};

export default sidebars;
