import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  foundationsSidebar:   [{type: 'autogenerated', dirName: '01-foundations'}],
  evaluationSidebar:    [{type: 'autogenerated', dirName: '02-evaluation'}],
  clinicalSidebar:      [{type: 'autogenerated', dirName: '03-clinical-conditions'}],
  surgicalSidebar:      [{type: 'autogenerated', dirName: '04-surgical-techniques'}],
  populationsSidebar:   [{type: 'autogenerated', dirName: '05-special-populations'}],
  journalSidebar:       [{type: 'autogenerated', dirName: '06-journal-club'}],
  rootsSidebar:         [{type: 'autogenerated', dirName: '07-roots'}],
  // Manual sidebar mirroring the Resources landing page (docs/08-resources/index.mdx)
  // section-stack — same items in the same order. History remains accessible
  // from About; the patient handout gallery is paused and intentionally unlisted.
  resourcesSidebar: [
    'resources/index',
    'resources/patient-resources',
    'resources/surgical-video-atlases',
    'resources/podcasts',
    'resources/textbooks',
    'resources/websites-online-tools',
    {
      type: 'category',
      label: 'Hidden Curriculum',
      link: {type: 'doc', id: 'resources/hidden-curriculum/index'},
      items: [{type: 'autogenerated', dirName: '08-resources/hidden-curriculum'}],
    },
  ],
};

export default sidebars;
