#!/usr/bin/env python3
"""Cross-page number consistency (audit plan item 3).

Groups pages that cover the same topic (duplicate filenames plus a few named sets), finds anchors
(trial names in capitals, or Author Year) mentioned on two or more pages of a group, and flags anchors
whose percentages or sample sizes do not overlap between pages. Writes reports/audit-v2/consistency.md.
Usage: python3 scripts/audit/consistency.py
"""
import re, pathlib, collections
ROOT = pathlib.Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
EXTRA = {
    "drug-coated-balloon": ["drug-coated-balloon", "drug-coated-balloon-therapy", "optilume-bph"],
    "urolift": ["urolift", "urolift-pul"],
    "rezum": ["rezum", "rezum-water-vapor-therapy"],
}
SKIP = {"index", "overview", "heaney", "iris", "propeller-flap", "nephropleural", "pyeloenteric", "ureterocolonic", "vesicocutaneous", "post-kidney-transplant", "non-binary-nullification", "testicular-reimplantation"}
ANCH = re.compile(r"\b([A-Z][A-Za-z\-]{3,}(?: et al\.?)? (?:19|20)\d\d|[A-Z]{4,}(?:-[A-Z0-9]+)?)\b")
PCT = re.compile(r"(\d+(?:\.\d+)?)\s?%")
NN = re.compile(r"\bn\s?=\s?(\d[\d,]*)")
NOISE = {"FDA", "MDPI", "AUA", "EAU", "SUFU", "NICE", "IFU", "ICIQ", "DOI", "PMID", "TURP", "BPH", "LUTS", "IPSS", "QMAX", "HTTPS", "HTML", "AUGS", "IUGA", "SUI", "OAB", "AUS", "MRI", "PSA"}

def stem_groups():
    by = collections.defaultdict(list)
    for f in DOCS.rglob("*.mdx"):
        by[f.stem].append(f)
    groups = {k: v for k, v in by.items() if len(v) > 1 and k not in SKIP}
    for name, stems in EXTRA.items():
        fs = [f for s in stems for f in by.get(s, [])]
        if len(fs) > 1:
            groups[name] = fs
    return groups

def body(f):
    t = f.read_text(errors="ignore")
    t = re.sub(r"^---.*?---", "", t, count=1, flags=re.S)
    return t.split("\n## References")[0]

def facts(f):
    out = collections.defaultdict(lambda: {"pct": set(), "n": set(), "snip": []})
    for para in re.split(r"\n\s*\n|(?<=[.!?])\s+(?=[A-Z])", body(f)):
        anchors = {a for a in ANCH.findall(para) if a not in NOISE}
        if not anchors:
            continue
        p = set(PCT.findall(para)); n = {x.replace(",", "") for x in NN.findall(para)}
        for a in anchors:
            out[a]["pct"] |= p; out[a]["n"] |= n
            if (p or n) and len(out[a]["snip"]) < 1:
                out[a]["snip"].append(para.strip().replace("\n", " ")[:160])
    return out

def main():
    L = ["# Cross-page consistency report", "", "Generated by `python3 scripts/audit/consistency.py`. An anchor is flagged when two pages in a group mention it and their percentage sets (or their n values) share no value. Many flags are different outcomes of one trial; each needs a look.", ""]
    total = 0
    for g, fs in sorted(stem_groups().items()):
        data = {str(f.relative_to(DOCS)): facts(f) for f in fs}
        pages = list(data)
        flags = []
        for a in set().union(*[set(d) for d in data.values()]):
            have = [p for p in pages if a in data[p] and (data[p][a]["pct"] or data[p][a]["n"])]
            for i in range(len(have)):
                for j in range(i + 1, len(have)):
                    x, y = data[have[i]][a], data[have[j]][a]
                    dis_p = x["pct"] and y["pct"] and not (x["pct"] & y["pct"])
                    dis_n = x["n"] and y["n"] and not (x["n"] & y["n"])
                    if dis_p or dis_n:
                        flags.append((a, have[i], have[j], sorted(x["pct"])[:6], sorted(y["pct"])[:6], sorted(x["n"])[:4], sorted(y["n"])[:4], x["snip"][:1], y["snip"][:1]))
        if flags:
            L += [f"## {g} ({len(fs)} pages)", ""]
            for a, p1, p2, x1, y1, n1, n2, s1, s2 in sorted(flags):
                total += 1
                L.append(f"- **{a}**: `{p1}` pct {x1} n {n1} vs `{p2}` pct {y1} n {n2}")
            L.append("")
    L.insert(3, f"**{total} flags.**"); L.insert(4, "")
    (ROOT / "reports/audit-v2/consistency.md").write_text("\n".join(L))
    print("flags", total)
main()
