#!/usr/bin/env python3
"""Build OpenEvidence question batches from the ledger -> reports/audit-v2/openevidence-prompts.md.
S1 and S2 claims only (dose, safety, guideline grade or wording). Only claims with a named published source (guideline, trial, Author Year); labels, IFUs, decisions and
unnamed claims are excluded. Batches of up to 6 claims per source; S1/S2 first."""
import sys, re, collections, pathlib, importlib.util
here = pathlib.Path(__file__).parent
spec = importlib.util.spec_from_file_location("ledger", here / "ledger.py")
led = importlib.util.module_from_spec(spec); spec.loader.exec_module(led)
rows, _ = led.build_rows()
SKIP = re.compile(r"unnamed|Drug labels|IFU|manual|SSED|decision|Paywalled|catalog|ProACT|Coloplast|document \(unnamed\)|AMS 800|operating room|MRI manuals|Original urethroplasty", re.I)
by = collections.defaultdict(list)
for r in rows:
    if r["disp"] != "waiting-on-source" or SKIP.search(r["src"]):
        continue
    if r["sev"] in ("S1", "S2"):
        by[r["src"]].append(r)
order = {"S1": 0, "S2": 1, "S3": 2, "S4": 3, "S5": 4}
L = ["# OpenEvidence question batches", "",
     "Generated by `python3 scripts/audit/oe_prompts.py`. Paste one block at a time. Return to Claude: the answer text plus, for each item, the document title, year and DOI/URL OpenEvidence cites. Claude checks the number against the cited source before any page change; OpenEvidence output alone is not cited on the site.", "",
     "Standard preamble to paste first in each session: *For each numbered item, answer only what the named source itself says. Quote the recommendation or figure verbatim with its grade or n. If the source does not say it, reply 'not stated'. Give the full citation (title, journal, year, DOI) for every quote.*", ""]
n = 0
for src_, rs in sorted(by.items(), key=lambda kv: (min(order[r["sev"]] for r in kv[1]), -len(kv[1]))):
    rs.sort(key=lambda r: order[r["sev"]])
    for i in range(0, len(rs), 6):
        chunk = rs[i:i + 6]; n += 1
        L.append(f"## Batch {n}: {src_} ({chunk[0]['sev']}{'+' if any(c['sev']!=chunk[0]['sev'] for c in chunk) else ''})")
        L.append("")
        L.append(f"Question: In {src_}, what does the source say about each of the following?")
        for j, c in enumerate(chunk, 1):
            L.append(f"{j}. {c['claim'][:200]} (page: `{c['page']}`)")
        L.append("")
pathlib.Path(here.parents[1] / "reports/audit-v2/openevidence-prompts.md").write_text("\n".join(x.rstrip() for x in L).rstrip() + "\n")
print("batches", n, "sources", len(by))
