#!/usr/bin/env python3
"""Check that every DOI in docs/ resolves and matches the cited reference (audit plan item 5).

Usage: python3 scripts/audit/refcheck.py            # run everything (cached), write reports/audit-v2/reference-check.md
       python3 scripts/audit/refcheck.py --limit 200  # quick test
Cache: reports/audit-v2/sources-local/refcheck-cache.json (gitignored).
A reference is flagged when Crossref (or the DOI handle service) cannot find the DOI, or when the
Crossref title shares under 40% of its words with the cited reference line, or the year differs by more than one.
"""
import html, json, re, sys, pathlib, urllib.request, urllib.parse, concurrent.futures as cf, collections, time

ROOT = pathlib.Path(__file__).resolve().parents[2]
CACHE = ROOT / "reports/audit-v2/sources-local/refcheck-cache.json"
OUT = ROOT / "reports/audit-v2/reference-check.md"
DOI = re.compile(r"10\.\d{4,9}/[^\s>\]\"'<]+")
REF = re.compile(r'^(?:<a id="ref[^"]*"></a>)+\s*(\d+)\.\s*(.*)$|^\[\^(\d+)\]:\s*(.*)$')
UA = {"User-Agent": "WARWIKI-refcheck/1.0 (mailto:warwikihq@gmail.com)"}
STOP = set("the of and for with in on a an to from by at as after versus vs study trial review patients".split())

def clean(d):
    d = urllib.parse.unquote(html.unescape(d.replace("\\", ""))).rstrip(".,;:")
    while d.endswith(")") and d.count(")") > d.count("("):
        d = d[:-1].rstrip(".,;:")
    return d

def words(s):
    return {w for w in re.findall(r"[a-z]{4,}", s.lower()) if w not in STOP}

def crossref(doi):
    url = "https://api.crossref.org/works/" + urllib.parse.quote(doi, safe="/")
    for i in range(3):
        try:
            with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=30) as r:
                m = json.load(r)["message"]
            yr = None
            for k in ("issued", "published-print", "published-online"):
                p = m.get(k, {}).get("date-parts", [[None]])[0]
                if p and p[0]:
                    yr = p[0]; break
            return {"ok": True, "title": " ".join(m.get("title") or []), "year": yr, "container": " ".join(m.get("container-title") or [])}
        except urllib.error.HTTPError as e:
            if e.code == 404:
                return handle(doi)
            time.sleep(2 * (i + 1))
        except Exception:
            time.sleep(2 * (i + 1))
    return {"ok": None, "err": "network"}

def handle(doi):
    try:
        with urllib.request.urlopen(urllib.request.Request("https://doi.org/api/handles/" + urllib.parse.quote(doi, safe="/"), headers=UA), timeout=30) as r:
            j = json.load(r)
        return {"ok": True, "title": "", "year": None, "note": "handle only (not Crossref)"} if j.get("responseCode") == 1 else {"ok": False}
    except urllib.error.HTTPError as e:
        return {"ok": False} if e.code == 404 else {"ok": None, "err": f"http {e.code}"}
    except Exception as e:
        return {"ok": None, "err": "network"}

def main():
    limit = int(sys.argv[sys.argv.index("--limit") + 1]) if "--limit" in sys.argv else None
    refs = []  # (page, n, line, [dois])
    for f in sorted((ROOT / "docs").rglob("*.mdx")):
        for line in f.read_text(errors="ignore").splitlines():
            m = REF.match(line.strip())
            if not m:
                continue
            body = m.group(2) if m.group(1) else m.group(4)
            ds = [clean(d) for d in DOI.findall(line)]
            if ds:
                refs.append((str(f.relative_to(ROOT / "docs")), m.group(1) or m.group(3), body, list(dict.fromkeys(ds))))
    allds = sorted({d for r in refs for d in r[3]})
    cache = json.loads(CACHE.read_text()) if CACHE.exists() else {}
    todo = [d for d in allds if d not in cache or cache[d].get("ok") is None][:limit]
    print(f"{len(refs)} references, {len(allds)} unique DOIs, {len(todo)} to look up", flush=True)
    done = 0
    with cf.ThreadPoolExecutor(8) as ex:
        for d, res in zip(todo, ex.map(crossref, todo)):
            cache[d] = res
            done += 1
            if done % 500 == 0:
                CACHE.write_text(json.dumps(cache)); print(done, flush=True)
    CACHE.write_text(json.dumps(cache))
    dead, mism, unk = [], [], []
    for page, n, body, ds in refs:
        for d in ds:
            c = cache.get(d)
            if not c or c.get("ok") is None:
                unk.append((page, n, d)); continue
            if c["ok"] is False:
                dead.append((page, n, d, body[:120])); continue
            t = c.get("title", "")
            if t:
                a, b = words(t), words(body)
                ov = len(a & b) / max(1, len(a))
                ym = re.search(r"\b(19|20)\d\d\b", body)
                yd = abs(int(ym.group(0)) - c["year"]) if ym and c.get("year") else 0
                if ov < 0.4 or yd > 1:
                    mism.append((page, n, d, round(ov, 2), c.get("year"), t[:90], body[:100]))
    L = ["# DOI check", "", f"Generated by `python3 scripts/audit/refcheck.py`. {len(refs)} references with DOIs, {len(allds)} unique DOIs.", "",
         f"- Not found in Crossref or the DOI handle service: **{len(dead)}**", f"- Title or year mismatch (Crossref title shares under 40% of words, or year differs by more than one): **{len(mism)}**",
         f"- Lookup failed (network): {len(unk)}", "", "## Not found", ""]
    L += [f"- `{p}` ref {n}: {d} | {b}" for p, n, d, b in dead]
    L += ["", "## Mismatch (review; many are abbreviated titles)", ""]
    L += [f"- `{p}` ref {n}: {d} | overlap {o}, Crossref year {y}: {t} | cited: {b}" for p, n, d, o, y, t, b in mism]
    OUT.write_text("\n".join(L))
    print("dead", len(dead), "mismatch", len(mism), "unknown", len(unk))
main()
