#!/usr/bin/env node
/**
 * WARWIKI stub tracker generator.
 *
 * Walks docs/ and detects stub articles (pages explicitly marked "*Stub — to
 * be built out.*" or equivalent, or very thin pages with <1500 chars).
 *
 * Reads docs/_STATUS.md if it exists, preserves any hand-edited priorities
 * and notes, and writes the merged result back. New stubs default to
 * priority 2 with empty notes. Files that are no longer stubs (filled out
 * in the meantime) are removed from the tracker.
 *
 * Run: node scripts/gen-status.js
 *
 * Summary is printed to stdout.
 */

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..');
const DOCS_DIR = path.join(REPO_ROOT, 'docs');
const STATUS_FILE = path.join(DOCS_DIR, '_STATUS.md');

const THIN_THRESHOLD = 1500; // chars

function walk(dir, files = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, files);
    else if (entry.name.endsWith('.mdx') || entry.name.endsWith('.md')) files.push(full);
  }
  return files;
}

// Components that wrap a whole page with dynamic content — these are NOT stubs
// even though their MDX source is tiny. The content lives in data/components.
const WRAPPER_COMPONENTS = [
  'SurgeonProfile',
  'GenericDatabase',
  'SurgeonsExplorer',
  'SurgeonDirectory',
  'SurgeonTree',
  'CurriculumViewer',
  'PodcastLibrary',
  'PodcastFeedList',
  'VideoCards',
];

function detectStub(content) {
  // Explicit stub marker (the site convention).
  if (/\*\s*Stub\s*[—–-]/i.test(content)) return 'marked';

  // Pages using a wrapper component are intentional shells, not stubs.
  if (WRAPPER_COMPONENTS.some((c) => new RegExp(`<\\s*${c}[\\s/>]`).test(content))) return null;

  // Strip frontmatter + imports + blank lines for real-content measurement.
  let body = content.replace(/^---[\s\S]*?^---\s*\n/m, '');
  body = body.replace(/^import\s+.+$/gm, '').replace(/^\s*$/gm, '').trim();

  // No H2 sections AND thin body = a shell without real content.
  const hasH2 = /^##\s+/m.test(body);
  if (!hasH2 && body.length < THIN_THRESHOLD) return 'thin';

  return null;
}

function loadExisting() {
  if (!fs.existsSync(STATUS_FILE)) return new Map();
  const content = fs.readFileSync(STATUS_FILE, 'utf8');
  const entries = new Map();
  // Parse | path | priority | notes | lines
  const lineRe = /^\|\s*`?([^`|]+?)`?\s*\|\s*(\d+)\s*\|\s*(.*?)\s*\|$/gm;
  let m;
  while ((m = lineRe.exec(content)) !== null) {
    const p = m[1].trim();
    if (p === 'Path' || p.startsWith('---')) continue;
    entries.set(p, { priority: parseInt(m[2], 10), notes: m[3] });
  }
  return entries;
}

function render(entries) {
  const rows = [...entries.entries()]
    .sort(([, a], [, b]) => a.priority - b.priority || 0)
    .map(([p, { priority, notes }]) => `| \`${p}\` | ${priority} | ${notes || ''} |`);

  const counts = { 1: 0, 2: 0, 3: 0 };
  for (const [, { priority }] of entries) counts[priority] = (counts[priority] || 0) + 1;

  const header = [
    '# WARWIKI Stub Tracker',
    '',
    'Auto-generated by `scripts/gen-status.js`. Run `npm run status` to regenerate.',
    'Priorities and notes are hand-edited and preserved across regenerations.',
    '',
    '**Priority scale:** `1` = fill soon (high-demand topic), `2` = normal, `3` = someday.',
    '',
    `**Totals:** ${entries.size} stubs — P1: ${counts[1] || 0}, P2: ${counts[2] || 0}, P3: ${counts[3] || 0}.`,
    '',
    '| Path | Priority | Notes |',
    '|---|---|---|',
  ].join('\n');

  return header + '\n' + rows.join('\n') + '\n';
}

function main() {
  const files = walk(DOCS_DIR);
  const existing = loadExisting();
  const stubs = new Map();

  for (const file of files) {
    const content = fs.readFileSync(file, 'utf8');
    const isStub = detectStub(content);
    if (!isStub) continue;
    const rel = path.relative(REPO_ROOT, file);
    const prev = existing.get(rel);
    stubs.set(rel, {
      priority: prev ? prev.priority : 2,
      notes: prev ? prev.notes : '',
    });
  }

  fs.writeFileSync(STATUS_FILE, render(stubs));

  const added = [...stubs.keys()].filter((k) => !existing.has(k)).length;
  const removed = [...existing.keys()].filter((k) => !stubs.has(k)).length;
  console.log(`Wrote ${STATUS_FILE.replace(REPO_ROOT + '/', '')}`);
  console.log(`  Total stubs: ${stubs.size}`);
  console.log(`  New since last run: ${added}`);
  console.log(`  Removed since last run: ${removed}`);
}

main();
