#!/usr/bin/env python3
"""Per-page quality scorecard: voice metrics, structure checks and Pass 1 coverage.

Usage: python3 scripts/consistency/scorecard.py   -> reports/2026-10-03/scorecard/scorecard.{json,md}
Voice rates come from scripts/voice/voice-report.py (per 1,000 prose words). Structure checks follow the CLAUDE.md
article pattern. Surgeon profiles, index pages and hide_title landing pages are scored for voice only.
Advisory: a high score marks a page to look at, not a defect.
"""
import json, re, pathlib, subprocess, collections

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "reports/2026-10-03/scorecard"
VOICE_KEYS = ["em_dash", "empty_evaluation", "generic_closer", "contrast_tic", "this_opener", "reader_address", "signposting", "arrow_in_prose"]


def structure(path, text):
    issues = []
    fm = re.match(r"^---\n(.*?)\n---", text, re.S)
    front = fm.group(1) if fm else ""
    if "hide_title: true" in front or path.name == "index.mdx" or "/07-roots/surgeons/" in str(path):
        return issues
    heads = re.findall(r"^## (.+)$", text, re.M)
    if "References" not in heads:
        issues.append("no References section")
    else:
        tail = heads[heads.index("References") + 1:]
        if tail:
            issues.append("sections after References: " + ", ".join(tail[:3]))
        if "Videos" in heads and heads.index("Videos") != heads.index("References") - 1:
            issues.append("Videos not immediately before References")
        if "See Also" in heads and "Videos" in heads and heads.index("See Also") > heads.index("Videos"):
            issues.append("See Also after Videos")
    body = text.split("\n## References")[0]
    first_para = next((p for p in re.split(r"\n\s*\n", body[fm.end() if fm else 0:]) if p.strip() and not p.lstrip().startswith(("#", "import", "<", "!", ">", "|", "---"))), "")
    if first_para and "<sup>" not in first_para and "[^" not in first_para:
        issues.append("no citation in opening paragraph")
    if re.search(r"^#{2,3} .*At a [Gg]lance", text, re.M):
        issues.append("At a glance block")
    if re.search(r"Would you like|As an AI|I hope this helps", body):
        issues.append("chatbot residue")
    if "evidenceUpdated" not in front and "lastReviewed" not in front:
        issues.append("no evidenceUpdated")
    refs = len(re.findall(r'<a id="ref\d+"></a>|^\[\^\d+\]:', text, re.M))
    words = len(re.findall(r"\w+", body))
    if words > 800 and refs < 5:
        issues.append(f"{refs} references for {words} words")
    return issues


def main():
    voice = json.loads(subprocess.check_output(["python3", "scripts/voice/voice-report.py", "docs", "--json"], cwd=ROOT))
    status = json.loads((ROOT / "reports/voice/status.json").read_text()).get("pages", {})
    rows = []
    for f in sorted((ROOT / "docs").rglob("*.mdx")):
        rel = str(f.relative_to(ROOT))
        v = voice["pages"].get(rel) or voice["pages"].get("docs/" + rel) or {}
        text = f.read_text()
        st = structure(f, text)
        vscore = sum(v.get(k, 0) for k in VOICE_KEYS)
        rows.append({"file": rel, "words": v.get("words", 0), "voice_score": round(vscore, 1),
                     "voice": {k: v.get(k, 0) for k in VOICE_KEYS if v.get(k)}, "pass1": rel in status or ("docs/" + rel) in status,
                     "structure": st})
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "scorecard.json").write_text(json.dumps(rows, indent=1))
    issue_counts = collections.Counter(re.sub(r"\d+ references for \d+ words", "few references for length", re.sub(r": .*", "", i)) for r in rows for i in r["structure"])
    no_pass1 = [r for r in rows if not r["pass1"] and r["words"] > 150]
    worst = sorted((r for r in rows if r["words"] > 300), key=lambda r: -r["voice_score"])[:40]
    lines = ["# Page scorecard (October 3, 2026)", "",
             f"Generated by `python3 scripts/consistency/scorecard.py`. {len(rows)} pages; site voice rates per 1,000 prose words: "
             + ", ".join(f"{k} {voice['site_per_1k'].get(k, 0)}" for k in VOICE_KEYS) + ".", "",
             f"Pages with more than 150 prose words and no voice Pass 1 record: **{len(no_pass1)}**.", "",
             "## Structure issues", "", "| Issue | Pages |", "|---|---|"]
    lines += [f"| {k} | {n} |" for k, n in issue_counts.most_common()]
    lines += ["", "## Highest voice scores (pages over 300 words)", "", "| Page | Words | Score | Pass 1 | Main signals |", "|---|---|---|---|---|"]
    for r in worst:
        sig = ", ".join(f"{k} {n}" for k, n in sorted(r["voice"].items(), key=lambda kv: -kv[1])[:3])
        lines.append(f"| `{r['file'].replace('docs/', '')}` | {r['words']} | {r['voice_score']} | {'yes' if r['pass1'] else 'no'} | {sig} |")
    (OUT / "scorecard.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines[:20]))


if __name__ == "__main__":
    main()
